CREATE TABLE EnterLog(
Id int IDENTITY(1, 1) PRIMARY KEY,
EnteredAt DATETIME DEFAULT GETDATE() NOT NULL,
UserId int NULL, 
UserLogin NVARCHAR(50),
Success bit,
FOREIGN KEY (UserId) REFERENCES USERS(userID) ON DELETE SET NULL
);